services:
  - type: web
    name: ads-portfolio
    env: python
    runtime: python-3.12
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py tailwind install &&
      python manage.py tailwind build &&
      python manage.py collectstatic --noinput
    startCommand: gunicorn ADS_Portfolio.wsgi:application
    region: ohio
    plan: free